# Generated by Django 5.2.4 on 2025-08-07 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_clientetoken_key'),
        ('facturacion', '0005_factura_iva_factura_subtotal_factura_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_transaccion', models.CharField(help_text='Código o comprobante de la transacción', max_length=100)),
                ('observacion', models.TextField(blank=True, help_text='Comentarios adicionales sobre el pago', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, help_text='Fecha y hora de validación', null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura')),
                ('pagado_por', models.ForeignKey(help_text='Cliente que realizó el pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='clientes.cliente')),
                ('validado_por', models.ForeignKey(blank=True, help_text='Usuario que aprobó o rechazó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
