# Generated by Django 5.2.4 on 2025-08-11 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_factura_estado_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'role': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
