# Generated by Django 5.2.4 on 2025-08-11 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='pagado_por',
            field=models.ForeignKey(help_text='Cliente que realizó el pago', limit_choices_to={'role': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
