# Generated by Django 5.2.4 on 2025-07-24 16:53

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_make_roles_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=secrets.token_hex, max_length=40, unique=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='clientes.cliente')),
            ],
        ),
    ]
