# Generated by Django 5.2.4 on 2025-07-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_clientetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientetoken',
            name='key',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
