# Generated by Django 5.2.4 on 2025-08-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_options_alter_cliente_managers_and_more'),
    ]

    operations = [
    ]
