# Generated by Django 5.2.4 on 2025-08-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20250811_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='role',
            field=models.CharField(default='Cliente', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClienteToken',
        ),
    ]
