# Generated by Django 5.2.4 on 2025-08-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_add_auth_fields'),
        ('clientes', '0008_alter_cliente_email_alter_cliente_role_and_more'),
    ]

    operations = [
    ]
