# Generated by Django 5.2.4 on 2025-08-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_merge_20250811_2114'),
    ]

    operations = [
        # Remove the Cliente model as all client data has been migrated to User model
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
