# Generated by Django 5.2.4 on 2025-08-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Secretario', 'Secretario'), ('Bodega', 'Bodega'), ('Ventas', 'Ventas'), ('Pagos', 'Pagos')], max_length=20, null=True),
        ),
    ]
