# Generated by Django 5.2.4 on 2025-08-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre completo del cliente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono del cliente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Secretario', 'Secretario'), ('Bodega', 'Bodega'), ('Ventas', 'Ventas'), ('Pagos', 'Pagos'), ('Cliente', 'Cliente')], max_length=20, null=True),
        ),
    ]
